name: Deploy to Hugging Face Space and Enable Remote Commands

on:
  push:
    branches:
      - main  # Triggers on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Authenticate and Push to Hugging Face Space
      - name: Push to Hugging Face Space
        env:
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://drogba771:${HUGGINGFACE_API_TOKEN}@huggingface.co/spaces/drogba771/command
          git pull origin main --rebase
          git push origin main

  run_locally:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      # Step 1: Check out the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set environment variables
      - name: Set Environment Variables
        run: echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}" >> $GITHUB_ENV

      # Step 5: Prompt user input for task parameter
      - name: Run app.py with User Input
        run: |
          echo "Please provide a task to execute with the model:"
          read USER_TASK
          python app.py --task "$USER_TASK"
