name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Hugging Face CLI Authentication
        run: |
          python -m pip install huggingface_hub
          huggingface-cli login --token ${{ secrets.HUGGINGFACE_API_KEY }}

      - name: Push to Hugging Face Space
        env:
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          git remote set-url origin https://huggingface.co/spaces/drogba771/commandandcontrol.git
          git push origin main
