name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Hugging Face CLI
      - name: Install Hugging Face CLI
        run: |
          python -m pip install huggingface_hub

      # Step 5: Authenticate with Hugging Face using the API token
      - name: Hugging Face Authentication
        run: |
          huggingface-cli login --token ${{ secrets.HUGGINGFACE_API_KEY }}

      # Step 6: Push to Hugging Face Space
      - name: Push to Hugging Face Space
        env:
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          git remote set-url origin https://huggingface.co/spaces/drogba771/commandandcontrol.git
          git push origin main
